file_format: "1"
id: croogpad
name: croogpad
type: shield
url: https://github.com/craigdav/zmk-config
requires:
  - pro_micro
exposes:
  - i2c_oled
features:
  - keys
  - display
  - encoder
  - underglow
  
